name: express_dt
description: A Dart library to easily create http servers and perform requests.
version: 1.0.4
homepage: https://github.com/Phelickz/dart_exp
authors:
 - Awa Felix <felixhope30@gmail.com> 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  path: ^1.8.0
  pedantic: ^1.11.0
  stack_trace: ^1.10.0
  crypto: ^3.0.1
  dotenv: ^3.0.0
  universal_io: ^2.0.4
  collection: ^1.15.0



  flutter:
    sdk: flutter

dev_dependencies:
  test:
  http:
  build_cli: ^2.1.2

  flutter_test:
    sdk: flutter

flutter:
